config/routes.rb
Rails.application.routes.draw do
  root "statics#home"
  resources :statics, only: [:home, :show]
  resources :menus, only: [:new, :show, :index]
  devise_for :users

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    post "/sessions/user" => "devise/sessions#create"
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :packs do
    resources :users_menus
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :user_menus, foreign_key: :menu_id
  has_many :packs, through: :user_menus
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!
  before_action :user_params, only: [:new, :index]

  def new
    @menu = Menu.new
    @menu.user_menus.build
    month_age_judg
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def index
    @menus = Menu.all
  end

  protected

  def month_age
    @user = current_user
    (Time.current.year - @user.birth_date.year) * 12 + Time.current.mon - @user.birth_date.mon - (Time.current.day >= @user.birth_date.day ? 0 : 1)
  end

  def month_age_judg
    if month_age < 7
      @best_age = "5-6ヶ月"
    elsif month_age < 9
      @best_age = "7-8ヶ月"
    else
      @best_age = "9-12ヶ月"
    end
  end

  def user_params
    params.permit(:name, :image, :recipe, :food_stuff, :best_age, :quantity)
  end
end

app/views/menus/index.html.erb
<% provide(:title, "メニュー一覧")%>
<div class = "container bg-light my-5">
  <h1 class = "border-bottom border-primary pt-4">メニュー一覧</h1>
  <div class="field form-group  mt-4">
    <div class="row">
      <% @menus.each do |menu| %>
        <div class = "col-md-4 text-center quantity prof_link my-3">
          <%= link_to menu_path(menu.id) do%>
            <%= image_tag "/#{menu.image}", class: "img-fluid rounded" %>
            <h5 class = text-dark><%= menu.name %></h5><br/>
          <% end %>
          <%= menu.best_age %>
        </div>
      <% end %>
    </div>
    <%= link_to 'javascript:history.back()' do %>
      <i class="mt-3 fas fa-arrow-circle-left fa-2x"></i>
    <% end %>
  </div>
</div>

app/views/menus/new.html.erb
<% provide(:title, "献立作成フォーム")%>
<div class = "container bg-light my-5">
  <h1 class= "border-bottom border-primary pt-4">献立作成フォーム</h1>
  <%= form_with url: new_pack_path, method: :get, local: true do |f| %>
    <div class="field form-group  mt-4">
      <div>
        <%= f.label :count, "作成食数" %>
        <%= f.select :count, [*1..21], class: "form-control col-sm-5" %>
      </div>
      <div>
        <%= f.label :best_age, "お子様の月齢" %>
        <%= f.select :best_age, ["5-6ヶ月", "7-8ヶ月", "9-12ヶ月"], {selected: @best_age}, class: "form-control col-sm-3 " %>
      </div>
    </div>
    <div class = "mt-4">
      <h6> アレルギー食材</h6>
    </div>
    <div class = "form-check px-1">
      <%= f.check_box :ng_food, { multiple: true}, "たまご", class: "form-check-input"%>
      <%= label :ng_food, "小麦" %>
      
      <%= f.check_box :ng_food, { multiple: true}, "牛乳",  class: "form-check-input"%>
      <%= label :ng_food, "卵" %>
      
      <%= f.check_box :ng_food, { multiple: true}, "パン", class: "form-check-input"%>
      <%= label :ng_food, "牛乳" %>
      
      <%= f.check_box :ng_food, { multiple: true}, "いか", class: "form-check-input"%>
      <%= label :ng_food, "えび" %>

      <%= f.check_box :ng_food, { multiple: true}, "トマト", class: "form-check-input"%>
      <%= label :ng_food, "かに" %>

      <%= f.check_box :ng_food, { multiple: true}, "トマト", class: "form-check-input "%>
      <%= label :ng_food, "そば" %>

      <%= f.check_box :ng_food, { multiple: true}, "トマト", class: "form-check-input "%>
      <%= label :ng_food, "落花生" %>
    </div>
    <div class="actions mt-4">
      <%= f.submit "作成", class: "btn btn-info" %>
    </div> 
  <% end %>
  <div class = "mt-2">
    <%= link_to "メニュー一覧", menus_path, class: "mt-1" %>
  </div>
  <div>
    <%= link_to 'javascript:history.back()' do %>
      <i class="mt-3 fas fa-arrow-circle-left fa-2x"></i>
    <% end %>
  </div>
</div>

app/views/menus/show.html.erb
<% provide(:title, "メニュー")%>
<div class = "container bg-light">
  <div class = "pt-3">
    <%= image_tag "/#{@menu.image}", class: "img-fluid rounded mx-auto d-block" %>
  </div>
  <div class = "text-center">
    <div>
      <h3><%= @menu.name%></h3>
    </div>
    <div>
      <h5><%= "対象月齢  #{@menu.best_age}" %></h5>
    </div>
    <div class = "row py-1">
      <div class = "col-sm-4 offset-2 text-left">
        <h4>---材料---</h4> 
        <%= simple_format@menu.quantity %>
      </div>
      <div class = "col-sm-6 text-left">
        <h4>---作り方---</h4>
        <h6><%= simple_format(@menu.recipe) %></h6>
      </div>
    </div>
  </div>
  <%= link_to 'javascript:history.back()' do %>
    <i class="mt-3 fas fa-arrow-circle-left fa-2x"></i>
  <% end %>
</div>