config/routes.rb
Rails.application.routes.draw do
  root "statics#home"
  resources :statics, only: [:home, :show]
  resources :menus, only: [:new, :show, :index]
  devise_for :users

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    post "/sessions/user" => "devise/sessions#create"
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :packs do
    resources :users_menus
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
    if user_signed_in?
      @user = current_user
      month_age
      redirect_to static_path(@user)
    end
  end

  def show
    @user = User.find(params[:id])
    @current_user = current_user
    month_age
    @packs = current_user.packs
  end

  def month_age
    @age = (Time.current.year - @user.birth_date.year) * 12 + Time.current.mon - @user.birth_date.mon - (Time.current.day >= @user.birth_date.day ? 0 : 1)
  end
end

app/views/statics/home.html.erb
<% provide(:title, "ホーム") %>
<div class= "container-fuild main-container mt-0">
  <div class = "row">
    <div class ="col-sm-3 mt-5">
      <h1 class="text-white bg-primary text-center rounded-pill">Foodo</h1>
    </div>
  </div>  
  <div class="row">
    <div class = "col-sm-3 text-center">
      <%= link_to  "新規登録", new_user_registration_path, class: 'btn btn-info rounded-lg col-lg-4 mt-2' %>
      <%= link_to  "ログイン", new_user_session_path, class: 'btn btn-success rounded-lg  col-lg-4 mt-2' %>
      <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class:"btn btn-success rounded-lg  m-3" %>
    </div>
  </div>
</div>
<div class="container text-center">
  <div class ="row">
    <h1 class="text-white  bg-info col-md-6 offset-md-3 mt-3 rounded-pill" id="about">Foodoとは</h1>
    <div class = "d-block mx-auto">
      <p class ="text-center">幼児食と一言で言っても実際は年齢によっても違いが出てきますし、<br class = "d-inline d-md-none"/>アレルギー食材は使用できない等、<br>毎日の幼児食を決めるのに疲れてしまっている<br class = "d-inline d-md-none"/>ママやパパはたくさんいます。</p>
    </div>
    <div class ="container-fuild">
      <div class=" row font-weight-bold">
        <div class="col-lg-4 my-4 bg-light">
          <%= image_tag "/月齢.jpeg", class: "rounded"  %>
          <h2>月齢別の献立</h2>
          <p> 月齢に合った献立を用意しています。</p>
        </div>
        <div class="col-lg-4 my-4 bg-light">
          <%= image_tag "/1週間.jpg"%>
          <h2>最大1週間分の作成可能</h2>
          <p>最大1週間分の献立作成可能</p>
        </div>
        <div class="col-lg-4 my-4 bg-light">
          <%= image_tag "/アレルギー.png" %>
          <h2>アレルギー食材除外</h2>
          <p>アレルギー食材や嫌いな食材などを入力するだけで<br class="d-inline d-sm-none"/>献立に入れないことも可能</p>
        </div>  
      </div>
    </div>  
  </div>
</div>

app/views/statics/show.html.erb
<% provide(:title, "ユーザー")%>
<div class = "container-fuild bg-white mt-5">
  <div class = "container pb-5 bg-light rounded pt-3">
    <div class = "row mx-auto">
      <div class=" col-12">
        <% if @user.image? %>
          <%= image_tag @user.image.thumb.url, class: "mx-auto d-block rounded-circle" %>
        <% else %>
          <%= image_tag"/no-image.png", class: "mx-auto d-block rounded-circle" %>
        <% end %>
      </div>
      <div class = "mt-3 col-sm-4 offset-sm-4">
        <div class = "prof mx-auto text-center w-sm-50">
          <h4><%= @user.name %></h4>
        </div>
        <div class = "prof mx-auto text-center w-sm-50">
          <h4><%=@age%>ヶ月</h4>
        </div>
      </div>
      <div class = "col-sm-4 text-center">
        <%= link_to new_menu_path do%>
          <i class="fas fa-utensils fa-3x fa-border menu_icon"></i>
        <% end %>
      </div>
    </div>
  </div>
  <%= render "layouts/pack_index" %>
  <div class = "container mb-4">
    <%= link_to 'javascript:history.back()' do %>
      <i class="mt-3 fas fa-arrow-circle-left fa-2x"></i>
    <% end %>
  </div>
</div>     