config/routes.rb
Rails.application.routes.draw do
  root "statics#home"
  resources :statics, only: [:home, :show]
  resources :menus, only: [:new, :show, :index]
  devise_for :users

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    post "/sessions/user" => "devise/sessions#create"
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :packs do
    resources :users_menus
  end
end

app/models/pack.rb
class Pack < ApplicationRecord
  belongs_to :user
  has_many :user_menus, foreign_key: :pack_id, dependent: :destroy
  has_many :menus, through: :user_menus
  accepts_nested_attributes_for :user_menus, allow_destroy: true
end

app/controllers/packs_controller.rb
class PacksController < ApplicationController
  before_action :authenticate_user!
  before_action :user_params, only: [:new]

  def new
    @user = current_user
    @pack = @user.packs.new
    @random = Menu.where(best_age: params[:best_age]).where.not(food_stuff: params[:ng_food]).order("RANDOM()").limit(params[:count])
    @count = params[:count]
  end

  def show
    @pack = Pack.find(params[:id])
    @menu = @pack.menus
  end

  def create
    @pack = current_user.packs.create(pack_params)
    @menu_ids = params[:menu_ids]
    @menu_ids.each do |p|
      @packs = @pack.user_menus.create(pack_id: @pack.id, menu_id: p)
    end
    flash[:notice] = "保存しました！"
    redirect_to static_path(current_user)
  end

  def edit
    @pack = Pack.find(params[:id])
    if @pack.user_id == current_user.id
      render "edit"
    end
  end

  def update
    @pack = Pack.find(params[:id])
    if @pack.user_id == current_user.id
      @pack.update(pack_params)
      flash[:notice] = "変更しました！"
      redirect_to pack_path(@pack)
    else
      render "show"
    end
  end

  def destroy
    pack = Pack.find(params[:id])
    if pack.user_id == current_user.id
      pack.destroy
      flash[:notice] = "削除しました！"
      redirect_to static_path(current_user)
    end
  end

  def user_params
    params.permit(:name, :image, :recipe, :food_stuff, :best_age, :quantity)
  end

  def pack_params
    params.require(:pack).permit(:name)
  end
end

app/views/packs/edit.html.erb
<% provide(:title, "献立編集")%>
<div class = "container bg-light my-5">
  <h2 class= "border-bottom border-primary pt-4">献立編集</h2>
  <%= form_with model: @pack, method: :put, local: true do |f| %>
    <div class="field form-group">
      <%= f.label :name, "献立名" %><br />
      <%= f.text_field :name, value: @pack.name, autofocus: true, autocomplete: "name", class: "form-control col-lg-5" %>
    </div>
    <div class="actions mt-4">
      <%= f.submit "更新", class: "btn btn-info login"%>
    </div>
  <% end %>
  <div>
    <p><%= button_to "献立を削除する", pack_path(@pack), data: { confirm: "献立を削除してよろしいですか?" }, method: :delete, class: "btn btn-danger" %></p>
  </div>
  <%= link_to 'javascript:history.back()' do %>
    <i class="mt-3 fas fa-arrow-circle-left fa-2x"></i>
  <% end %>
</div>

app/views/packs/new.html.erb
<% provide(:title, "献立作成")%>
<div class = "container bg-light my-5">
  <h1 class = "border-bottom border-primary pt-4">献立作成</h1>
  <div class="field form-group  mt-4">
    <%= form_for(@pack) do |f| %>
      <div class="row">
        <% @random.each do |menu| %>
          <div class = "col-md-4 text-center quantity prof_link my-3">
            <%= hidden_field_tag "user_id", current_user.id %>
            <%= hidden_field_tag "menu_ids[]", menu.id %>
            <%= link_to menu_path(menu.id) do%>
              <%= image_tag "/#{menu.image}", class: "img-fluid rounded" %>
              <h5 class = text-dark><%= menu.name %></h5><br/>
            <% end %>
            <%= simple_format(menu.quantity) %>
          </div>
        <% end %>
      </div>
      <div class = "field form-group"> 
        <%= f.label :name, "献立名" %>
        <%= f.text_field :name, value:"#{Time.current.to_date}作成(#{@count}食分)", class: "form-control col-lg-5" %>
      </div>
      <div class="actions mt-4">
        <%= f.submit "保存", class: "btn btn-info" %>
      </div>
    <% end %>
    <%= link_to 'javascript:history.back()' do %>
      <i class="mt-3 fas fa-arrow-circle-left fa-2x"></i>
    <% end %>
  </div>
</div>

app/views/packs/show.html.erb
<% provide(:title, @pack.name)%>
<div class = "container bg-light my-5">
  <h1 class = "border-bottom border-primary pt-4">献立</h1>
  <h2><%= @pack.name %></h2>
  <%= link_to  "献立名の編集", edit_pack_path(@pack) %>
  <div class="field form-group  mt-4">
    <div class="row">
      <% @menu.each do |menu| %>
        <div class = "col-md-4 text-center quantity prof_link my-3">
          <%= link_to menu_path(menu.id) do%>
            <%= image_tag "/#{menu.image}", class: "img-fluid rounded" %>
            <h5 class = text-dark><%= menu.name %></h5><br/>
          <% end %>
          <%= simple_format(menu.quantity) %>
        </div>
      <% end %>
    </div>
    <%= link_to 'javascript:history.back()' do %>
      <i class="mt-3 fas fa-arrow-circle-left fa-2x"></i>
    <% end %>
  </div>
</div>