config/routes.rb
Rails.application.routes.draw do
  root "statics#home"
  resources :statics, only: [:home, :show]
  resources :menus, only: [:new, :show, :index]
  devise_for :users

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    post "/sessions/user" => "devise/sessions#create"
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :packs do
    resources :users_menus
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer bg-dark">
  <div class="text-lg-left container">
    <p><%=link_to "Foodo", root_path, class: "text-white"%></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="header navbar navbar-expand-sm navbar-dark bg-dark sticky-top h5">
  <%= link_to  "Foodo", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id ="navbarNav4">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item mr-2">
          <%= link_to "ホーム", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item mx-2">
          <%= link_to "献立作成", new_menu_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown ml-2 mr-5">
          <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            ユーザー
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "マイページ", static_path(current_user), class: "dropdown-item" %>
            <%= link_to "プロフィール変更", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Foodoについて", root_path(anchor: "about"), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>    

app/views/layouts/_pack_index.html.erb
<div class = "container shadow p-3 mb-5 mt-5 bg-light rounded">
  <h2>献立一覧</h2>
  <% if @packs.present? %>
    <table class="table table-hover text-center">
      <thead >
        <tr class = "row">
          <th class = "col-2">NO</th>
          <th class = "col-6">献立名</th>
          <th class = "col-2">作成日</th>
          <th class = "col-2">削除する</th>
        </tr>
      </thead>
      <% @packs.each_with_index do |pack, i| %>
        <tbody>
          <tr class = "row">
            <th class = "col-2"><%= i+1 %></th>
            <td class = "col-6 text-body"><%= link_to pack.name, pack_path(pack.id), class: "text-dark prof_link" %></td>
            <td class = "col-2"><%= pack.created_at.strftime('%y/%m/%d') %></td>
            <td class = "col-2"><%= button_to "削除", pack_path(pack.id), data: { confirm: "削除してよろしいですか?" }, method: :delete %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tag %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!-- viewport meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- style.css -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- FontAwesome5 -->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <% if notice %>
      <p class = "alert alert-success"><%= notice %></p>
    <% end %>  
    <% if alert %>
      <p class = "alert alert-warning"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>